<h1>Pagina de Editar</h1>
<hr>

<form action="#" method="post">
    <label>Nome</label>
    <input type="text" name="nome" value="<?php echo $aluno["nome"]; ?>">

    <label>Matricula</label>
    <input type="text" name="matricula" value="<?php echo $aluno["matricula"]; ?>">

    <label>Cidade</label>
    <input type="text" name="cidade" value="<?php echo $aluno["cidade"]; ?>">

    <button type="submit">Editar</button>
</form>